### PR TITLE
Update to version 2.2.0

### PR DESCRIPTION
**Pull request by DenysMb**

### CODE REVIEW

**Comment by DenysMBarbosa** [comment]
@hfiguiere Can you check this?

**Comment by DenysMb** [comment]
@hfiguiere can you check this?

**Comment by hfiguiere** [comment]
what do you want me to do? I'm not the maintainer.

**Comment by DenysMb** [comment]
> what do you want me to do? I'm not the maintainer.

Sorry. Since you merged the last one, I thought that you were the one that could merge this PR.
I think that there is no maintainer for this at the moment.
It should be me, but when I went to accept the invitation, it was already expired.
(I went away for a few months because I got married and moved to another country.)

**Comment by hfiguiere** [comment]
your are the original submitter. you should be able to merge.

**Comment by DenysMb** [comment]
Unfortunally I can't. 😢
I don't have write access.

image

**Comment by hfiguiere** [comment]
You should have had:

**Comment by hfiguiere** [comment]
image

**Comment by hfiguiere** [comment]
@barthalion can you resend the invite? ^^^^

**Comment by barthalion** [comment]
I just sent a new one.

**Comment by DenysMb** [comment]
> I just sent a new one.

Thank you!

**Pull request merged**
